[platformio]
src_dir = cardfix-core/src
include_dir = cardfix-core/include
test_dir = tests

env_default = native

[env:native]
platform = native
build_flags = 
    -std=c++17
    -Icardfix-core/include
lib_extra_dirs = cardfix-core
