[platformio]
src_dir = src
include_dir = include

[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
build_flags =
    -std=gnu++17
lib_deps =
    m5stack/M5Unified
    m5stack/M5GFX
lib_extra_dirs = ../cardfix-core
